# Generated by Django 4.1.2 on 2022-11-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regiser', models.CharField(max_length=150)),
                ('rating', models.FloatField()),
                ('dlitelnost', models.IntegerField()),
            ],
        ),
    ]
