# Generated by Django 4.1.2 on 2022-11-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_film_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
